### ISSUE TITLE
Possible bug: No voice navigation

### ISSUE THREAD

**Issue by Framstag** [janbar/osmin#14]
Up to now I started navigation and listened to the voice navigation. Yesterday I started a route but there was no voice navigation. Visual navigation worked though. 

Up to the start I listened to podcasts via car bluethooth. So it is possible that it is not the fault of the application but a general android or podcast player problem (have similar effects during running, where time for kilometer is not voiced, too).

I stopped the podcast quickly but still now voice (I did not start osmin again though)., 

Nevertheless you should know ;-), perhaps there is a setting, switch, callback or similar...

**Comment by janbar** [comment]
I had the same issue because my phone was connecting to the bluetooth of the car. Then I changed the audio source in the car-screen-board. It worked but not very well because Bluetooth make some time gap and sometimes cut the speech before the end. So the root cause isn't in the app, but instead how the phone/car handle the stream and playback.

**Comment by Framstag** [comment]
OK, you can close the issue.
